# Update these values for your GitHub org and SonarQube project.
sonar.projectKey=wallet-transfer-assignment
sonar.projectName=wallet-transfer-assignment
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.exclusions=**/.git/**,**/.github/**,**/target/**
